Jan 15 22:01:36.634 - [ERROR] xxnet_version fail:IOError(2, 'No such file or directory')
Jan 15 22:01:36.635 - [ERROR] Except stack:Traceback (most recent call last):
  File "C:\Users\wuqing\Desktop\FirefoxPortable\launcher\update_from_github.py", line 92, in parse_readme_versions
    fd = open(readme_file, "r")
IOError: [Errno 2] No such file or directory: 'C:\\Users\\wuqing\\Desktop\\FirefoxPortable\\README.md'

Jan 15 22:01:36.635 - [INFO] start XX-Net get_version_fail
Jan 15 22:01:36.635 - [DEBUG] start confirm_xxnet_exit
Jan 15 22:01:37.639 - [DEBUG] good, xxnet:8087 cleared!
Jan 15 22:01:38.684 - [DEBUG] good, xxnet:8085 clear!
Jan 15 22:01:38.684 - [DEBUG] finished confirm_xxnet_exit
Jan 15 22:01:41.862 - [INFO] module gae_proxy started
Jan 15 22:01:41.862 - [INFO] start gae_proxy time cost 3170
Jan 15 22:01:41.862 - [INFO] begin to start web control
Jan 15 22:01:41.864 - [INFO] launcher web control started.
Jan 15 22:03:15.870 - [DEBUG] start to terminate gae_proxy module
Jan 15 22:03:15.979 - [INFO] module gae_proxy stopped
